### ISSUE TITLE
Backward compat - rc_django shouldn't need to be added to INSTALLED_APPS

### ISSUE THREAD

**Issue by vegitron** [uw-it-aca/uw-restclients-django-utils#8]
The error:

restclients/restclients/models/__init__.py", line 25, in <module>
   from rc_django.models import CacheEntry, CacheEntryTimed     RuntimeError: Model class rc_django.models.CacheEntry doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

The models should declare an explicit app_label, so people using uw_restclients don't need to change settings based on behind the scenes changes

**Comment by jlaney** [comment]
Fixed with 0.5.2.
